files:
  include:
    - 'radix.scss'
    - 'radix/**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*'
    - 'tests/**/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  attribute-quotes: 2,
  # This has a conflict with placeholder names
  #bem-depth:
  #  - max-depth: 1
  border-zero: 2
  brace-style:
    - 2
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: hyphenatedbem
  clean-import-paths:
    - 2
    - filename-extension: false
    - leading-underscore: false
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: true
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - convention: hyphenatedlowercase
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: uppercase
  id-name-format:
    - 2
    - convention: hyphenatedbem
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: true
  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase
  nesting-depth:
    - 2
    - max-depth: 2
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 1
  no-debug: 1
  no-empty-rulesets: 1
  no-extends: 2
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 2
  no-qualifying-elements: 1
  no-trailing-zero: 2
  no-url-protocols: 2
  no-vendor-prefixes:
    - 2
    - ignore-non-standard: true
  placeholder-in-extend: 1
  placeholder-name-format: 0
  property-sort-order:
    - 2
    - ignore-custom-properties: false
      order: concentric
  quotes:
    - 2
    - style: single
  shorthand-values: 1
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma: 2
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon:
    - 2
    - include: true
  url-quotes: 1
  variable-for-property: 1
  variable-name-format:
    - 1
    - convention: hyphenatedlowercase
  zero-unit: 1